db:
    image: postgres 
web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    links:
        - db

migration:
    image: fuai2_web
    command: python manage.py makemigrations face
    volumes:
        - .:/code
migrate:
    image: fuai2_web
    command: python manage.py migrate
    volumes:
        - .:/code
